/// Flutter icons Icones
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icones
///      fonts:
///       - asset: fonts/Icones.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Icones {
  Icones._();

  static const _kFontFam = 'Icones';

  static const IconData mosquito = IconData(0xe801, fontFamily: _kFontFam);
}
